---
- name: this playbook install apache2
  hosts: dbservers
  become: True
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
  - name: start apache2 service
    service:
      name: apache2
      state: started
