---
- name: this playbook setup tomcat
  hosts: all
  become: True
  tasks:

  - name: install java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
  
  - name: download tomcat packages
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-10/v10.0.4/bin/apache-tomcat-10.0.4.tar.gz
      dest: /opt

  - name: unzip tomcat download
    unarchive:
      src: /opt/apache-tomcat-10.0.4.tar.gz
      dest: /opt
      remote_src: yes

  - name: add execution permission to startup.sh file
    file:
      path: /opt/apache-tomcat-10.0.4/bin/startup.sh
      mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-10.0.4/bin
